#!/bin/bash
source ./bits/bootstrap/logging
set -euo pipefail ; IFS=$'\n\t'

#-----------
# Configurations
#-----------

LAUNCHER_OWNER=${LAUNCHER_OWNER-$USER}
export LAUNCHER_DIR=${LAUNCHER_DIR-/var/local}
export REDIS_LAUNCHER_DIR=${REDIS_LAUNCHER_DIR-$LAUNCHER_DIR/redis}
export REDIS_LOG_DIR=${REDIS_LOG_DIR-/var/log/redis}
export REDIS_CONFIG_DIR=${REDIS_CONFIG_DIR-$REDIS_LAUNCHER_DIR/config}
export REDIS_DATA_DIR=${REDIS_DATA_DIR-/var/local/redis/data}
export REDIS_PORT=${REDIS_PORT-6379}
export REDIS_HOST=${REDIS_HOST-"127.0.0.1:"}
REDIS_VERSION=${REDIS_VERSION-default}

#-----------
# Install Script
#-----------

notify "Installing REDIS..."

OWNER=$LAUNCHER_OWNER ./bits/bootstrap/mkdir \
  LAUNCHER_DIR \
  REDIS_LAUNCHER_DIR \
  REDIS_LOG_DIR \
  REDIS_DATA_DIR \
  REDIS_CONFIG_DIR \
  ${REDIS_LAUNCHER_DIR}/src

notify "  -- Copying config files"

TEMPLATE=./bits/redis/files/redis.conf LOCATION=${REDIS_CONFIG_DIR}/redis.conf ./bits/docker/copyif

if [[ "$REDIS_VERSION" != "default" ]]; then
  REDIS_SRC_FILE=${REDIS_LAUNCHER_DIR}/src/redis-${REDIS_VERSION}.tar.gz
  if [[ ! -e $REDIS_SRC_FILE ]]; then
    (cd ${REDIS_LAUNCHER_DIR}/src/ && wget http://download.redis.io/releases/redis-${REDIS_VERSION}.tar.gz)
  fi
  TEMPLATE=./bits/redis/files/redis_version.dockerfile LOCATION=$REDIS_LAUNCHER_DIR/Dockerfile ./bits/docker/copyif
  sed -i "s|@REDIS_VERSION@|$REDIS_VERSION|g" ${REDIS_LAUNCHER_DIR}/Dockerfile
else
  TEMPLATE=./bits/redis/files/redis_default.dockerfile LOCATION=$REDIS_LAUNCHER_DIR/Dockerfile ./bits/docker/copyif
fi

LAUNCHER_DIR=$REDIS_LAUNCHER_DIR NAME=redis ./bits/docker/build

notify "  -- Creating helper scripts"
NAME=redis DIR=$REDIS_LAUNCHER_DIR \
  START=./bits/redis/files/_start \
  DEBUG=./bits/redis/files/_debug \
  ./bits/docker/helpers


notify "DONE, Installing REDIS."
