#!/bin/bash

#-----------
# Configurations
#-----------

REDIS_LAUNCHER_DIR=${REDIS_LAUNCHER_DIR-/var/local/redis}
REDIS_LOG_DIR=${REDIS_LOG_FILE-/var/log/redis}
REDIS_DATA_DIR=${REDIS_DATA_DIR-/var/local/redis/data}
REDIS_PORT=${REDIS_PORT-6379}

DEBUG=${DEBUG-false}

#-----------
# Install Script
#-----------

echo "Installing REDIS..."

mkdir -p ${REDIS_LAUNCHER_DIR} ${REDIS_LOG_DIR} ${REDIS_DATA_DIR}

cp ./submodules/redis/files/redis.dockerfile ${REDIS_LAUNCHER_DIR}/Dockerfile
cp -u ./submodules/redis/files/redis.conf ${REDIS_LAUNCHER_DIR}/redis.conf

DEBUG=$DEBUG LAUNCHER_DIR=$REDIS_LAUNCHER_DIR NAME=redis ./submodules/docker/build

echo "#!/bin/bash
docker run -i -t \\
  -v ${REDIS_LOG_DIR}:/log \\
  -v ${REDIS_DATA_DIR}:/data \\
  --link redis:rdb \\
  redis /bin/bash
" > ${REDIS_LAUNCHER_DIR}/debug

printf "%b" "#!/bin/bash
docker rm redis > /dev/num
docker run -d -t \\
  -p ${REDIS_PORT}:6379 \\
  -v ${REDIS_LOG_DIR}:/log \\
  -v ${REDIS_DATA_DIR}:/data \\
  --name redis \\
  redis
" > ${REDIS_LAUNCHER_DIR}/start

NAME=redis DIR=$REDIS_LAUNCHER_DIR ./submodules/docker/stop
NAME=redis DIR=$REDIS_LAUNCHER_DIR ./submodules/docker/idempot
NAME=redis DIR=$REDIS_LAUNCHER_DIR ./submodules/docker/ip

chmod 755 $REDIS_LAUNCHER_DIR/start
chmod 755 $REDIS_LAUNCHER_DIR/debug
chmod 755 $REDIS_LAUNCHER_DIR/ip

echo "DONE, Installing REDIS."